#!/usr/bin/env python3
"""
Export public catalog data to database/seed_public.sql.

Included tables:
  - artists
  - genres
  - albums (created_by forced to NULL)
  - album_genres
  - tracks

Excluded user-related tables:
  - users, favorites, reviews, blog_*, notifications, events, question_banks,
    and online match tables
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
from pathlib import Path
from typing import Iterable

import pymysql


EXPORT_TABLES = [
    (
        "artists",
        [
            "id",
            "name",
            "name_initial",
            "country",
            "formed_year",
            "genre",
            "member_count",
            "status",
            "description",
            "photo_url",
            "created_at",
        ],
    ),
    ("genres", ["id", "name", "description"]),
    (
        "albums",
        [
            "id",
            "title",
            "title_initial",
            "artist_id",
            "release_year",
            "cover_url",
            "description",
            "created_by",
            "created_at",
            "updated_at",
        ],
    ),
    ("album_genres", ["album_id", "genre_id"]),
    ("tracks", ["id", "album_id", "track_number", "title", "duration"]),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export non-user seed SQL for open-source bootstrap.")
    parser.add_argument("--db-host", default=os.getenv("DB_HOST", "127.0.0.1"))
    parser.add_argument("--db-port", type=int, default=int(os.getenv("DB_PORT", "3306")))
    parser.add_argument("--db-name", default=os.getenv("DB_NAME", "music_review"))
    parser.add_argument("--db-user", default=os.getenv("DB_USER", "music_review_app"))
    parser.add_argument("--db-pass", default=os.getenv("DB_PASS", ""))
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent / "seed_public.sql"),
        help="Output SQL path",
    )
    return parser.parse_args()


def sql_value(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (dt.datetime, dt.date, dt.time)):
        value = value.isoformat(sep=" ")
    text = str(value)
    text = (
        text.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )
    return f"'{text}'"


def fetch_rows(conn, table: str, cols: Iterable[str]):
    order = cols[0]
    sql = f"SELECT {', '.join(cols)} FROM {table} ORDER BY {order}"
    with conn.cursor() as cur:
        cur.execute(sql)
        return cur.fetchall()


def main() -> int:
    args = parse_args()
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    conn = pymysql.connect(
        host=args.db_host,
        port=args.db_port,
        user=args.db_user,
        password=args.db_pass,
        database=args.db_name,
        charset="utf8mb4",
        cursorclass=pymysql.cursors.Cursor,
        autocommit=True,
    )

    try:
        with out_path.open("w", encoding="utf-8") as f:
            f.write("-- Public seed dataset (no user data)\n")
            f.write("-- Generated by database/export_public_seed.py\n\n")
            f.write("USE music_review;\n")
            f.write("SET NAMES utf8mb4;\n")
            f.write("SET FOREIGN_KEY_CHECKS=0;\n\n")

            f.write("TRUNCATE TABLE tracks;\n")
            f.write("TRUNCATE TABLE album_genres;\n")
            f.write("TRUNCATE TABLE albums;\n")
            f.write("TRUNCATE TABLE genres;\n")
            f.write("TRUNCATE TABLE artists;\n\n")

            for table, cols in EXPORT_TABLES:
                rows = fetch_rows(conn, table, cols)
                if not rows:
                    continue
                f.write(f"-- {table}: {len(rows)} rows\n")
                col_sql = ", ".join(f"`{c}`" for c in cols)
                for row in rows:
                    values = list(row)
                    if table == "artists":
                        photo_index = cols.index("photo_url")
                        photo = values[photo_index]
                        if isinstance(photo, str) and photo.startswith("/api/files/"):
                            values[photo_index] = None
                    if table == "albums":
                        cover_index = cols.index("cover_url")
                        cover = values[cover_index]
                        if isinstance(cover, str) and cover.startswith("/api/files/"):
                            values[cover_index] = None
                        created_by_index = cols.index("created_by")
                        values[created_by_index] = None
                    values_sql = ", ".join(sql_value(v) for v in values)
                    f.write(f"INSERT INTO `{table}` ({col_sql}) VALUES ({values_sql});\n")
                f.write("\n")

            f.write("SET FOREIGN_KEY_CHECKS=1;\n")
    finally:
        conn.close()

    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
